name: ninety_nine_days_of_flutter
description: Attempting 99 designs on Flutter as a complete novice!
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.10.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  location: ^5.0.3
  provider: ^6.0.5
  stroke_text: ^0.0.2
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/day_1/
    - assets/images/day_5/
    - assets/images/day_7/
    - assets/images/day_8/
    - assets/images/day_9/
