// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaW4ro-bxPcpG97B7cMtBpEp-O5ZG0r0U',
    appId: '1:47373252800:web:7f4c92176c73fd9de35525',
    messagingSenderId: '47373252800',
    projectId: 'day-12---flutter-x-firebase',
    authDomain: 'day-12---flutter-x-firebase.firebaseapp.com',
    storageBucket: 'day-12---flutter-x-firebase.appspot.com',
    measurementId: 'G-K89WGYGFLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-nAHWXx9f_auHVhkZOhcvYo4TR0uY2bQ',
    appId: '1:47373252800:android:df1810c7a7803a5ce35525',
    messagingSenderId: '47373252800',
    projectId: 'day-12---flutter-x-firebase',
    storageBucket: 'day-12---flutter-x-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr6w9KwVp5dnSVD99sZlSQKYJCleqgwmY',
    appId: '1:47373252800:ios:50210d2a8cc52205e35525',
    messagingSenderId: '47373252800',
    projectId: 'day-12---flutter-x-firebase',
    storageBucket: 'day-12---flutter-x-firebase.appspot.com',
    iosBundleId: 'com.example.ninetyNineDaysOfFlutter',
  );
}
