// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZFttb33S2cQzMUe7lkPn1mN-B5eDvT_I',
    appId: '1:62197690780:web:0f114c924303a782231859',
    messagingSenderId: '62197690780',
    projectId: 'todo-ui-design-fa938',
    authDomain: 'todo-ui-design-fa938.firebaseapp.com',
    storageBucket: 'todo-ui-design-fa938.appspot.com',
    measurementId: 'G-VHVRG4KK0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Nw53ZLj4DL9_Pjvw_UugyUX-rb7s15Q',
    appId: '1:62197690780:android:d763711e50ade867231859',
    messagingSenderId: '62197690780',
    projectId: 'todo-ui-design-fa938',
    storageBucket: 'todo-ui-design-fa938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQt_OUbBMZyg6mGWjINPcjT8wpgyKiHaE',
    appId: '1:62197690780:ios:5e9b26958857a7d0231859',
    messagingSenderId: '62197690780',
    projectId: 'todo-ui-design-fa938',
    storageBucket: 'todo-ui-design-fa938.appspot.com',
    iosBundleId: 'com.example.ninetyNineDaysOfFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQt_OUbBMZyg6mGWjINPcjT8wpgyKiHaE',
    appId: '1:62197690780:ios:90b240add776e613231859',
    messagingSenderId: '62197690780',
    projectId: 'todo-ui-design-fa938',
    storageBucket: 'todo-ui-design-fa938.appspot.com',
    iosBundleId: 'com.example.ninetyNineDaysOfFlutter.RunnerTests',
  );
}
